### PR TITLE
Mute members who self-gaol

### PR DESCRIPTION
**Pull request by Scrub000**
This PR extends the 'self-jail' functionality to also temporarily mute members for the time specified. This should prevent any unwanted activity within the '#dunce-corner' channel.

Replaces PR https://github.com/strinking/futaba/pull/350.

### CODE REVIEW

**Comment by Ma-wa-re** [comment]
Changes to the channel will be required

**Comment by ammongit** [comment]
what does "gaol" mean

**Comment by Scrub000** [comment]
> what does "gaol" mean

Another way to spell "jail". :)

**Comment by ammongit** [comment]
that is really weird and not intuitive imo

**Pull request merged**
